import json
from pathlib import Path

import numpy as np
import pandas as pd
import geopandas as gpd
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
from shapely.geometry import Polygon, LineString
from pyproj import Transformer

from ipywidgets import Layout, Output, VBox, HBox, ToggleButtons, HTML, Button
from ipyleaflet import Map, GeoData, GeoJSON, basemaps, CircleMarker, LayerGroup, WidgetControl
from IPython.display import display, clear_output

def extract_transient_data(gwf, base_heads, obs_csv_path):
    """
    Extract transient head arrays from a MODFLOW 6 model output, calculate 
    drawdown relative to a steady-state base, and format observation time series.

    Parameters
    ----------
    gwf : flopy.mf6.ModflowGwf
        The active MODFLOW 6 groundwater flow model object.
    base_heads : numpy.ndarray
        A 3D array of initial steady-state heads used as the baseline for 
        calculating drawdown.
    obs_csv_path : str or pathlib.Path
        The file path to the grid observation CSV output file generated by MODFLOW.

    Returns
    -------
    dict
        A dictionary containing the compiled transient data:
        - 'times' (numpy.ndarray): Array of simulation elapsed times.
        - 'heads' (numpy.ndarray): 4D array of head values (time, layer, row, col).
        - 'drawdown' (numpy.ndarray): 4D array of calculated drawdown (base_heads - heads).
        - 'hydrograph' (pandas.DataFrame): DataFrame containing time, head, and 
          drawdown values for each observation point.
        - 'obs_cols' (list of str): List of the observation point names.
    """
    head_file = gwf.output.head()
    times = np.array(head_file.get_times())
    heads_all = head_file.get_alldata()
    
    layer_botm = gwf.modelgrid.botm
    for i in range(len(times)):
        heads_all[i] = np.where(heads_all[i] > 1e20, layer_botm, heads_all[i])
        
    drawdown_all = base_heads - heads_all

    obs_df = pd.read_csv(obs_csv_path)
    obs_cols = [c for c in obs_df.columns if c.lower() != "time"]
    
    initial_heads = {}
    strt_array = gwf.ic.strt.array
    for obs in obs_cols:
        parts = obs.split("_")
        l = int(parts[1].lower().replace("l", "")) - 1
        r = int(parts[2].lower().replace("r", "")) - 1
        c = int(parts[3].lower().replace("c", "")) - 1
        initial_heads[obs] = strt_array[l, r, c]
        
    initial_row = pd.DataFrame([[0.0] + [initial_heads[o] for o in obs_cols]], columns=["time"] + obs_cols)
    hydrograph_df = pd.concat([initial_row, obs_df[["time"] + obs_cols]], ignore_index=True)
    
    drawdown_dict = {f"{obs}_drawdown": hydrograph_df[obs].iloc[0] - hydrograph_df[obs] for obs in obs_cols}
    hydrograph_df = pd.concat([hydrograph_df, pd.DataFrame(drawdown_dict)], axis=1)

    return {
        "times": times,
        "heads": heads_all,
        "drawdown": drawdown_all,
        "hydrograph": hydrograph_df,
        "obs_cols": obs_cols
    }

def build_static_features(gwf, shp_path, layer_for_wells=8):
    """
    Build GeoJSON representations and GeoDataFrames of static model features 
    for interactive mapping.

    This function extracts the model bounding box, clips provided county 
    boundaries to the domain, and generates polygons for wells, streamflow 
    routing (SFR), and general-head boundaries (GHB).

    Parameters
    ----------
    gwf : flopy.mf6.ModflowGwf
        The active MODFLOW 6 groundwater flow model object.
    shp_path : str or pathlib.Path
        The file path to the county boundaries shapefile.
    layer_for_wells : int, optional
        The zero-indexed layer number from which to extract well (WEL) geometries. 
        Defaults to 8.

    Returns
    -------
    dict
        A dictionary containing the compiled spatial features:
        - 'counties' (geopandas.GeoDataFrame): Clipped county boundaries in EPSG:4326.
        - 'model_bbox' (geopandas.GeoDataFrame): Bounding box of the model domain in EPSG:4326.
        - 'wells_geojson' (dict or None): GeoJSON dictionary of well cell polygons.
        - 'sfr_geojson' (dict or None): GeoJSON dictionary of SFR cell polygons.
        - 'ghb_geojson' (dict or None): GeoJSON dictionary of GHB cell polygons.
    """
    modelgrid = gwf.modelgrid
    
    xmin, xmax, ymin, ymax = modelgrid.extent
    bbox_poly = Polygon([(xmin, ymin), (xmax, ymin), (xmax, ymax), (xmin, ymax)])
    bbox_gdf = gpd.GeoDataFrame(geometry=[bbox_poly], crs="EPSG:5070").to_crs(epsg=4326)
    
    counties = gpd.read_file(shp_path).to_crs(epsg=4326)
    counties_clipped = gpd.clip(counties, bbox_gdf)
    
    wel_polygons, sfr_polygons, ghb_polygons = [], [], []
    
    if gwf.wel is not None:
        for rec in gwf.wel.stress_period_data.get_data()[0]:
            l, r, c = rec['cellid']
            if l == layer_for_wells:
                wel_polygons.append(Polygon(modelgrid.get_cell_vertices(r, c)))
                
    if gwf.sfr is not None:
        for rec in gwf.sfr.packagedata.array:
            l, r, c = rec['cellid']
            if l == 0:
                sfr_polygons.append(Polygon(modelgrid.get_cell_vertices(r, c)))

    if gwf.ghb is not None:
        for rec in gwf.ghb.stress_period_data.get_data()[0]:
            l, r, c = rec['cellid']
            if l == 0:
                ghb_polygons.append(Polygon(modelgrid.get_cell_vertices(r, c)))

    def to_geojson(polys):
        if not polys: return None
        gdf = gpd.GeoDataFrame(geometry=polys, crs="EPSG:5070").to_crs(epsg=4326)
        return json.loads(gdf.to_json())

    return {
        "counties": counties_clipped,
        "model_bbox": bbox_gdf,
        "wells_geojson": to_geojson(wel_polygons),
        "sfr_geojson": to_geojson(sfr_polygons),
        "ghb_geojson": to_geojson(ghb_polygons)
    }

def generate_contours(array_2d, gwf, mode, vmin, vmax):
    """
    Generate spatial contour lines for a 2D array of model results using 
    fixed global limits and convert them to a styled GeoJSON payload.

    Parameters
    ----------
    array_2d : numpy.ndarray
        A 2D array of model results (e.g., heads or drawdown) for a specific 
        time step and layer.
    gwf : flopy.mf6.ModflowGwf
        The active MODFLOW 6 groundwater flow model object.
    mode : str
        The active display mode, typically 'Drawdown' or 'Head'. Dictates the 
        matplotlib colormap applied to the contours.
    vmin : float
        The global minimum value used to anchor the contour levels and color 
        normalization.
    vmax : float
        The global maximum value used to anchor the contour levels and color 
        normalization.

    Returns
    -------
    tuple
        A tuple containing two elements:
        - c_json (dict or None): A GeoJSON dictionary of the contour lines with 
          assigned hex colors, or None if no contours could be generated.
        - unique_vals (list of float): A sorted list (descending) of the discrete 
          contour values generated for building map legends.
    """
    subset = np.where((array_2d > 1e20) | (array_2d < -1e20), np.nan, array_2d)
    
    # If the array is perfectly flat (e.g., drawdown at time 0)
    if np.nanmax(subset) == np.nanmin(subset):
        return None, []
        
    X = gwf.modelgrid.xcellcenters
    Y = gwf.modelgrid.ycellcenters
    
    # Generate 15 strictly anchored intervals based on the global minimum and maximum
    fixed_levels = np.linspace(vmin, vmax, 15)
    
    fig_d, ax_d = plt.subplots()
    
    # Try plotting contours; if it fails (e.g., values don't cross the fixed levels), catch it safely
    try:
        cs = ax_d.contour(X, Y, subset, levels=fixed_levels)
        
        lines, vals = [], []
        for i, level_segs in enumerate(cs.allsegs):
            val = cs.levels[i]
            for seg in level_segs:
                if len(seg) > 1:
                    lines.append(LineString(seg))
                    vals.append(val)
    except Exception:
        plt.close(fig_d)
        return None, []
        
    plt.close(fig_d)
    
    if not lines: return None, []
        
    c_gdf = gpd.GeoDataFrame({'value': vals}, geometry=lines, crs="EPSG:5070").to_crs(epsg=4326)
    cmap_name = 'magma' if mode == 'Drawdown' else 'viridis'
    
    # Anchor the color normalization to the global limits
    norm = mcolors.Normalize(vmin=vmin, vmax=vmax)
    cmap = mpl.colormaps.get_cmap(cmap_name)
    c_gdf['color'] = c_gdf['value'].apply(lambda x: mcolors.to_hex(cmap(norm(x))))
    
    return json.loads(c_gdf.to_json()), sorted(list(set(vals)), reverse=True)


class DroughtDashboard:
    """
    Interactive dashboard with globally anchored limits and map hovering.

    This class provides a user interface combining an ipyleaflet map and a 
    matplotlib plot to explore transient groundwater model results (heads 
    and drawdown) across multiple time steps.

    Parameters
    ----------
    gwf : flopy.mf6.ModflowGwf
        The active MODFLOW 6 groundwater flow model object.
    data : dict
        A dictionary containing extracted transient data including times, 
        4D head arrays, 4D drawdown arrays, and hydrograph DataFrames.
    static_features : dict
        A dictionary of GeoJSON objects and GeoDataFrames representing 
        static model features (e.g., bounding box, counties, streams, wells, ghb).
    layer : int, optional
        The zero-indexed model layer to visualize on the map. Default is 8.

    Attributes
    ----------
    gwf : flopy.mf6.ModflowGwf
        The groundwater flow model object.
    data : dict
        The transient data payload.
    layer : int
        The active model layer being visualized.
    times : numpy.ndarray
        Array of simulation times (in days).
    time_idx : int
        The current index of the active time step being displayed.
    mode : str
        The current display mode, either 'Drawdown' or 'Head'.
    selected_obs : str or None
        The name of the currently selected observation point.
    head_min : float
        The global minimum head value across all time steps for the active layer.
    head_max : float
        The global maximum head value across all time steps for the active layer.
    dd_min : float
        The global minimum drawdown value across all time steps for the active layer.
    dd_max : float
        The global maximum drawdown value across all time steps for the active layer.
    transformer : pyproj.Transformer
        Coordinate transformer for converting map interactions (WGS84) to model CRS (EPSG:5070).
    plot_output : ipywidgets.Output
        The widget output context for the matplotlib hydrograph.
    toggle : ipywidgets.ToggleButtons
        Widget to switch between 'Drawdown' and 'Head' modes.
    btn_prev : ipywidgets.Button
        Widget button to step to the previous time step.
    btn_next : ipywidgets.Button
        Widget button to step to the next time step.
    timestep_label : ipywidgets.HTML
        Widget displaying the current time step index and elapsed time.
    info_label : ipywidgets.HTML
        Widget displaying instructions or the currently selected observation point.
    hover_label : ipywidgets.HTML
        Widget displaying the value of the cell currently being hovered over on the map.
    m : ipyleaflet.Map
        The interactive map instance.
    contour_group : ipyleaflet.LayerGroup
        The map layer group containing the dynamically generated contours.
    legend_html : ipywidgets.HTML
        Widget displaying the dynamically updated contour color legend.
    obs_group : ipyleaflet.LayerGroup
        The map layer group containing the interactive observation grid markers.
    marker_dict : dict
        A mapping of observation point names to their respective `ipyleaflet.CircleMarker` objects.
    """
    
    def __init__(self, gwf, data, static_features, layer=8):
        self.gwf = gwf
        self.data = data
        self.layer = layer
        
        self.times = data["times"]
        self.time_idx = 0
        self.mode = "Drawdown"
        self.selected_obs = None
        
        # Calculate Global Limits for Contouring
        self._calculate_global_limits()
        
        # Fast coordinate transformer for the mouse hover (WGS84 Lat/Lon -> EPSG:5070 X/Y)
        self.transformer = Transformer.from_crs("EPSG:4326", "EPSG:5070", always_xy=True)
        
        self.plot_output = Output()
        self._build_controls()
        self._build_map(static_features)
        self._wire_events()
        
        self.update_contours()
        self.render_hydrograph()

    def _calculate_global_limits(self):
        """
        Identify the true min and max across all time steps for the active layer.
        
        This sets the `head_min`, `head_max`, `dd_min`, and `dd_max` attributes 
        used to anchor the contour maps to a consistent color scale.
        """
        # 1. Heads global limits
        layer_heads = self.data["heads"][:, self.layer, :, :]
        active_heads = np.where((layer_heads > 1e20) | (layer_heads < -1e20), np.nan, layer_heads)
        self.head_min = np.nanmin(active_heads)
        self.head_max = np.nanmax(active_heads)
        
        # 2. Drawdown global limits
        layer_dd = self.data["drawdown"][:, self.layer, :, :]
        active_dd = np.where((layer_dd > 1e20) | (layer_dd < -1e20), np.nan, layer_dd)
        self.dd_min = np.nanmin(active_dd)
        self.dd_max = np.nanmax(active_dd)

    def _build_controls(self):
        """Initialize the interactive IPyWidgets for the dashboard interface."""
        self.toggle = ToggleButtons(options=['Drawdown', 'Head'], description='Display:', button_style='info')
        self.btn_prev = Button(icon='step-backward', tooltip='Previous Timestep', layout=Layout(width='40px'), disabled=True)
        self.btn_next = Button(icon='step-forward', tooltip='Next Timestep', layout=Layout(width='40px'))
        self.timestep_label = HTML(value=f"<b>Timestep:</b> {self.time_idx + 1} / {len(self.times)} ({self.times[self.time_idx]:.2f} Days)")
        self.info_label = HTML(value="<i>Click an observation point to view its hydrograph.</i>")
        self.hover_label = HTML(value=f"<b>Hovered {self.mode}:</b> <i>None</i>")

    def _build_map(self, static_features):
        """
        Construct the static layers, bounds, and observation markers for the map.

        Parameters
        ----------
        static_features : dict
            The pre-compiled dictionary of GeoJSON geometries.
        """
        bbox_gdf = static_features["model_bbox"]
        tb = bbox_gdf.total_bounds
        center = ((tb[1] + tb[3]) / 2, (tb[0] + tb[2]) / 2)
        
        self.m = Map(basemap=basemaps.Esri.WorldTopoMap, center=center, zoom=9, layout=Layout(height='750px'))
        
        self.m.add(GeoJSON(data=json.loads(bbox_gdf.to_json()), style={'color': '#000000', 'fillOpacity': 0, 'weight': 2, 'dashArray': '5, 5'}, name="Model Domain"))
        self.m.add(GeoData(geo_dataframe=static_features["counties"], style={'color': '#FF5F05', 'fillOpacity': 0, 'weight': 1.0}, name="Counties"))
        
        self.contour_group = LayerGroup(name="Contours")
        self.m.add(self.contour_group)
        self.legend_html = HTML()
        self.m.add(WidgetControl(widget=self.legend_html, position='bottomright'))

        if static_features["ghb_geojson"]:
            self.m.add(GeoJSON(data=static_features["ghb_geojson"], style={'fillColor': '#00FFFF', 'color': '#13294B', 'weight': 0.5, 'fillOpacity': 0.8}, name="Lake Michigan"))
        if static_features["sfr_geojson"]:
            self.m.add(GeoJSON(data=static_features["sfr_geojson"], style={'fillColor': '#0055FF', 'color': '#13294B', 'weight': 0.5, 'fillOpacity': 0.8}, name="Streams"))
        if static_features["wells_geojson"]:
            self.m.add(GeoJSON(data=static_features["wells_geojson"], style={'fillColor': '#FF0000', 'color': '#13294B', 'weight': 1, 'fillOpacity': 0.8}, name="Layer 9 Wells"))

        self.obs_group = LayerGroup(name="Grid Observations")
        self.m.add(self.obs_group)
        self.marker_dict = {}
        
        for obs in self.data["obs_cols"]:
            parts = obs.split("_")
            r = int(parts[2].lower().replace("r", "")) - 1
            c = int(parts[3].lower().replace("c", "")) - 1
            x, y = self.gwf.modelgrid.xcellcenters[r, c], self.gwf.modelgrid.ycellcenters[r, c]
            pt = gpd.GeoDataFrame(geometry=[gpd.points_from_xy([x], [y])[0]], crs="EPSG:5070").to_crs(epsg=4326)
            
            marker = CircleMarker(location=(pt.geometry.y.iloc[0], pt.geometry.x.iloc[0]), radius=6, color='#13294B', fill_color='#FF5F05', fill_opacity=0.6, weight=1)
            marker.on_click(self._make_obs_callback(obs))
            self.obs_group.add(marker)
            self.marker_dict[obs] = marker

    def _wire_events(self):
        """Bind interactive UI and map events to their respective callbacks."""
        self.toggle.observe(self._on_toggle, names='value')
        self.btn_prev.on_click(self._on_prev)
        self.btn_next.on_click(self._on_next)
        self.m.on_interaction(self._on_map_interaction)

    def _on_map_interaction(self, **kwargs):
        """
        Callback for map interactions. Mathematically converts cursor 
        Lat/Lon to Model Row/Col on the fly to display cell values.
        """
        if kwargs.get('type') == 'mousemove':
            lat, lon = kwargs.get('coordinates')
            x, y = self.transformer.transform(lon, lat)
            
            try:
                r, c = self.gwf.modelgrid.intersect(x, y)
                if r >= 0 and c >= 0:
                    target_array = self.data["drawdown"] if self.mode == 'Drawdown' else self.data["heads"]
                    val = target_array[self.time_idx, self.layer, r, c]
                    
                    if val is None or val > 1e20 or val < -1e20:
                        disp = "Inactive"
                    else:
                        disp = f"{val:.2f} m"
                        
                    self.hover_label.value = f"<b>Hovered {self.mode} (Row {r+1}, Col {c+1}):</b> {disp}"
            except Exception:
                self.hover_label.value = f"<b>Hovered {self.mode}:</b> <i>Outside domain</i>"

    def _make_obs_callback(self, obs_name):
        """
        Closure to generate a callback function for a specific observation marker.
        
        Parameters
        ----------
        obs_name : str
            The name of the observation point to bind to the click event.
            
        Returns
        -------
        function
            The configured event handler.
        """
        def callback(event, **kwargs):
            self.selected_obs = obs_name
            self.info_label.value = f"<b>Selected Observation:</b> <span style='color:#FF5F05'>{obs_name}</span>"
            for name, marker in self.marker_dict.items():
                if name == obs_name:
                    marker.radius, marker.fill_color, marker.color, marker.weight, marker.fill_opacity = 9, '#FFFFFF', '#FF5F05', 4, 1.0
                else:
                    marker.radius, marker.fill_color, marker.color, marker.weight, marker.fill_opacity = 6, '#FF5F05', '#13294B', 1, 0.6
            self.render_hydrograph()
        return callback

    def _on_toggle(self, change):
        """Callback to handle switching between Head and Drawdown modes."""
        if change['new']:
            self.mode = change['new']
            self.hover_label.value = f"<b>Hovered {self.mode}:</b> <i>None</i>"
            self.update_contours()
            self.render_hydrograph()

    def _on_prev(self, b):
        """Callback to decrement the time step."""
        if self.time_idx > 0: self._set_time_index(self.time_idx - 1)

    def _on_next(self, b):
        """Callback to increment the time step."""
        if self.time_idx < len(self.times) - 1: self._set_time_index(self.time_idx + 1)

    def _set_time_index(self, idx):
        """
        Master method to update internal state, GUI labels, contours, and 
        hydrographs when the active time step changes.
        
        Parameters
        ----------
        idx : int
            The new time step index.
        """
        self.time_idx = idx
        self.timestep_label.value = f"<b>Timestep:</b> {idx + 1} / {len(self.times)} ({self.times[idx]:.2f} Days)"
        self.btn_prev.disabled = (idx == 0)
        self.btn_next.disabled = (idx == len(self.times) - 1)
        self.update_contours()
        self.render_hydrograph()

    def update_contours(self):
        """
        Generate and update the contour overlay for the active time step and mode.
        
        Extracts the appropriate 2D array, computes contours anchored to the 
        global min/max, converts them to GeoJSON, and updates the map and legend.
        """
        # 1. Determine which global limits to use
        if self.mode == 'Drawdown':
            vmin, vmax = self.dd_min, self.dd_max
        else:
            vmin, vmax = self.head_min, self.head_max
            
        # 2. Extract current timestep array and run contour engine
        target_array = self.data["drawdown"] if self.mode == 'Drawdown' else self.data["heads"]
        array_2d = target_array[self.time_idx, self.layer]
        
        c_json, unique_vals = generate_contours(array_2d, self.gwf, self.mode, vmin, vmax)
        
        self.contour_group.layers = ()
        if c_json:
            def contour_style(feature): return {'color': feature['properties']['color'], 'weight': 3, 'opacity': 0.8}
            self.contour_group.add(GeoJSON(data=c_json, style_callback=contour_style))
            
            # 3. Update HTML Legend using global normalization
            cmap_name = 'magma' if self.mode == 'Drawdown' else 'viridis'
            norm = mcolors.Normalize(vmin=vmin, vmax=vmax)
            cmap = mpl.colormaps.get_cmap(cmap_name)
            
            legend = f"<div style='background: white; padding: 10px; color: black; border-radius: 5px; opacity: 0.9;'><b>{self.mode} (m)</b><br>"
            for v in unique_vals:
                c = mcolors.to_hex(cmap(norm(v)))
                legend += f"<i style='background:{c}; width: 12px; height: 12px; display: inline-block; margin-right: 5px;'></i> {v:.2f}<br>"
            legend += "</div>"
            self.legend_html.value = legend
        else:
            self.legend_html.value = "<div style='background: white; padding: 10px; border-radius: 5px; opacity: 0.9;'><b>No contours found</b><br><i>(Head difference is 0)</i></div>"

    def render_hydrograph(self):
        """
        Render the matplotlib hydrograph corresponding to the active view state.
        
        Plots all grid observation locations faintly, highlights the actively 
        selected observation point, and anchors a vertical line to the current 
        simulation time step.
        """
        with self.plot_output:
            clear_output(wait=True)
            fig, ax = plt.subplots(figsize=(12, 4))
            df = self.data["hydrograph"]
            
            for obs in self.data["obs_cols"]:
                y_col = obs if self.mode == "Head" else f"{obs}_drawdown"
                alpha, lw, color = (1.0, 3, '#FF5F05') if obs == self.selected_obs else (0.15, 1, '#13294B')
                z = 10 if obs == self.selected_obs else 1
                ax.plot(df["time"], df[y_col], linewidth=lw, color=color, alpha=alpha, zorder=z)

            ax.axvline(self.times[self.time_idx], color='gray', linestyle='--', alpha=0.7, label="Current Time")
            ax.set_xlabel("Days into Drought")
            ax.set_ylabel(f"{self.mode} (m)")
            ax.set_title(f"Grid Observations - Mode: {self.mode}")
            
            if self.mode == 'Drawdown': ax.invert_yaxis()
            ax.grid(True, alpha=0.3)
            plt.tight_layout()
            plt.show()

    def display(self):
        """Assemble the Jupyter Widgets VBox layout and mount the dashboard."""
        header = HTML(value="<h2>Interactive Drought Scenario Viewer</h2>")
        top_row = HBox([self.toggle, self.hover_label, self.info_label], layout={'align_items': 'center', 'justify_content': 'space-between', 'margin': '0 0 10px 0'})
        control_row = HBox([self.btn_prev, self.btn_next, self.timestep_label], layout={'align_items': 'center', 'margin': '0 0 10px 0'})
        dashboard = VBox([header, top_row, control_row, self.m, self.plot_output])
        display(dashboard)
